services:
    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - backend
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
